/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.55
 * Generated at: 2020-05-23 09:23:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import vo.GradeVO;
import java.util.List;
import dao.GradeDAO;

public final class grade_005fview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("dao.GradeDAO");
    _jspx_imports_classes.add("vo.GradeVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");

	/* DB 검색 */
	GradeDAO gdao = GradeDAO.getInstance();
	List<GradeVO> grade_list = gdao.selectList();

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t\t<title>학생 성적 정보 조회</title>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\tfunction del( no ){\r\n");
      out.write("\t\t\t\tif( !confirm(\"정말로 삭제하시겠습니까? \")){\r\n");
      out.write("\t\t\t\t\treturn; /* 취소버튼을 눌렀을 때 */\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//삭제\r\n");
      out.write("\t\t\t\tlocation.href = \"grade_del.jsp?no=\" + no ; /* location.href : 해당 페이지로 화면전환 , 파라미터로 no를 같이 보낸다.*/\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//입력창 보여주기\r\n");
      out.write("\t\t\tfunction show_form(){\r\n");
      out.write("\t\t\t\tvar disp = document.getElementById(\"disp\");\r\n");
      out.write("\t\t\t\tdisp.style.display = \"block\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//입력창 숨기기\r\n");
      out.write("\t\t\tfunction hide_form(){\r\n");
      out.write("\t\t\t\tvar disp = document.getElementById(\"disp\");\r\n");
      out.write("\t\t\t\tvar disp2 = document.getElementById(\"disp2\");\r\n");
      out.write("\t\t\t\tdisp.style.display = \"none\";\r\n");
      out.write("\t\t\t\tdisp2.style.display = \"none\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t/* 입력상자 비우기 */\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"m_name\").value = \"\";\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"m_kor\").value = \"\";\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"m_eng\").value = \"\";\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"m_mat\").value = \"\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction send( f ){\r\n");
      out.write("\t\t\t\t/* 공백제거 */\r\n");
      out.write("\t\t\t\tvar name = f.name.value.trim();\r\n");
      out.write("\t\t\t\tvar kor = f.kor.value.trim();\r\n");
      out.write("\t\t\t\tvar eng = f.eng.value.trim();\r\n");
      out.write("\t\t\t\tvar mat = f.mat.value.trim();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t/* 유효성 체크 */\r\n");
      out.write("\t\t\t\tif(name == \"\"){\r\n");
      out.write("\t\t\t\t\talert(\"이름은 반드시 입력해야 합니다\");\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar num_pattern = /^[0-9]+$/;\r\n");
      out.write("\t\t\t\tif( !num_pattern.test(kor) || kor < 0 || kor > 100){\r\n");
      out.write("\t\t\t\t\talert(\"성적은 0-100 사이의 정수를 입력해야 합니다\");\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif( !num_pattern.test(eng) || eng < 0 || eng > 100){\r\n");
      out.write("\t\t\t\t\talert(\"성적은 0-100 사이의 정수를 입력해야 합니다\");\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif( !num_pattern.test(mat) || mat < 0 || mat > 100){\r\n");
      out.write("\t\t\t\t\talert(\"성적은 0-100 사이의 정수를 입력해야 합니다\");\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tf.action = \"grade_register.jsp\"\r\n");
      out.write("\t\t\t\tf.submit();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* 학생 정보 수정 */\r\n");
      out.write("\t\t\tfunction update( no, name, kor, eng, mat ){\r\n");
      out.write("\t\t\t\tvar disp2 = document.getElementById(\"disp2\");\r\n");
      out.write("\t\t\t\tdisp2.style.display = \"block\";\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"m_no2\").value = no;\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"m_name2\").value = name;\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"m_kor2\").value = kor;\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"m_eng2\").value = eng;\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"m_mat2\").value = mat;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction send2( f ){\r\n");
      out.write("\t\t\t\tvar no = f.no.value.trim();\r\n");
      out.write("\t\t\t\tvar name2 = f.name2.value.trim();\r\n");
      out.write("\t\t\t\tvar kor2 = f.kor2.value.trim();\r\n");
      out.write("\t\t\t\tvar eng2 = f.eng2.value.trim();\r\n");
      out.write("\t\t\t\tvar mat2 = f.mat2.value.trim();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t/* 유효성 체크 */\r\n");
      out.write("\t\t\t\tif(name2 == \"\"){\r\n");
      out.write("\t\t\t\t\talert(\"이름은 반드시 입력해야 합니다\");\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar num_pattern = /^[0-9]+$/;\r\n");
      out.write("\t\t\t\tif( !num_pattern.test(kor2) || kor2 < 0 || kor2 > 100){\r\n");
      out.write("\t\t\t\t\talert(\"성적은 0-100 사이의 정수를 입력해야 합니다\");\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif( !num_pattern.test(eng2) || eng2 < 0 || eng2 > 100){\r\n");
      out.write("\t\t\t\t\talert(\"성적은 0-100 사이의 정수를 입력해야 합니다\");\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif( !num_pattern.test(mat2) || mat2 < 0 || mat2 > 100){\r\n");
      out.write("\t\t\t\t\talert(\"성적은 0-100 사이의 정수를 입력해야 합니다\");\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tf.action = \"grade_update.jsp\"\r\n");
      out.write("\t\t\t\tf.submit();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<!-- 이름 국어 영어 수학 총점 평균 -->\r\n");
      out.write("\t\t<table border = \"1\">\r\n");
      out.write("\t\t\t<caption>== 학생 성적 정보 ==</caption>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>이름</th>\r\n");
      out.write("\t\t\t\t<th>국어</th>\r\n");
      out.write("\t\t\t\t<th>영어</th>\r\n");
      out.write("\t\t\t\t<th>수학</th>\r\n");
      out.write("\t\t\t\t<th>총점</th>\r\n");
      out.write("\t\t\t\t<th>평균</th>\r\n");
      out.write("\t\t\t\t<th>등수</th>\r\n");
      out.write("\t\t\t\t<th colspan = \"2\">비고</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");
 for(int i = 0; i < grade_list.size(); i++){ 
					GradeVO vo = grade_list.get(i);
			
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>");
      out.print( vo.getName() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print( vo.getKor() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print( vo.getEng() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print( vo.getMat() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print( vo.getTot() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print( vo.getAvg() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print( vo.getRank() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type = \"button\" value = \"삭제\" onclick=\"del('");
      out.print( vo.getNo() );
      out.write("');\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type = \"button\" value = \"수정\" \r\n");
      out.write("\t\t\t\t\t\tonclick=\"update('");
      out.print( vo.getNo() );
      out.write("', \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t'");
      out.print( vo.getName() );
      out.write("',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t'");
      out.print( vo.getKor() );
      out.write("',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t'");
      out.print( vo.getEng() );
      out.write("',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t'");
      out.print( vo.getMat() );
      out.write("');\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\t\t\t\t\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan = \"9\" align = \"center\">\r\n");
      out.write("\t\t\t\t\t<input type = \"button\" value = \"학생추가\" id=\"bt_append\" onclick=\"show_form();\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<!-- 학생추가 폼 -->\r\n");
      out.write("\t\t<div id = \"disp\" style=\"display:none\">\r\n");
      out.write("\t\t\t<form>\r\n");
      out.write("\t\t\t\t<table border = \"1\">\r\n");
      out.write("\t\t\t\t\t<caption>성적 입력</caption>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>이름</th>\r\n");
      out.write("\t\t\t\t\t\t<td><input name=\"name\" id=\"m_name\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>국어</th>\r\n");
      out.write("\t\t\t\t\t\t<td><input name=\"kor\" id=\"m_kor\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>영어</th>\r\n");
      out.write("\t\t\t\t\t\t<td><input name=\"eng\" id=\"m_eng\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>수학</th>\r\n");
      out.write("\t\t\t\t\t\t<td><input name=\"mat\" id=\"m_mat\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan = \"2\" align = \"center\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type = \"button\" value = \"등록\" onclick=\"send(this.form);\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type = \"button\" value = \"취소\" onclick=\"hide_form();\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 학생수정 폼 -->\r\n");
      out.write("\t\t<div id = \"disp2\" style=\"display:none\">\r\n");
      out.write("\t\t\t<form>\r\n");
      out.write("\t\t\t\t<table border = \"1\">\r\n");
      out.write("\t\t\t\t\t<caption>성적 수정</caption>\r\n");
      out.write("\t\t\t\t\t<input type = \"hidden\" name = \"no\" id = \"m_no2\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>이름</th>\r\n");
      out.write("\t\t\t\t\t\t<td><input name=\"name2\" id=\"m_name2\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>국어</th>\r\n");
      out.write("\t\t\t\t\t\t<td><input name=\"kor2\" id=\"m_kor2\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>영어</th>\r\n");
      out.write("\t\t\t\t\t\t<td><input name=\"eng2\" id=\"m_eng2\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>수학</th>\r\n");
      out.write("\t\t\t\t\t\t<td><input name=\"mat2\" id=\"m_mat2\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan = \"2\" align = \"center\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type = \"button\" value = \"수정\" onclick=\"send2(this.form);\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type = \"button\" value = \"취소\" onclick=\"hide_form();\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
