//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Study_ASP.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_User
    {
        public int USR_Index { get; set; }
        public int POS_Index { get; set; }
        public int LEV_Index { get; set; }
        public string USR_Code { get; set; }
        public string USR_Name { get; set; }
        public string USR_Email { get; set; }
        public string USR_Password { get; set; }
        public int USR_IsAdmin { get; set; }
        public int USR_IsDeveloper { get; set; }
        public int USR_IsChief { get; set; }
        public int USR_IsTeamAdmin { get; set; }
        public int USR_IsMilitary { get; set; }
        public Nullable<int> USR_birthdayMonth { get; set; }
    }
}
