-- # VIEW : 원하는 정보만 추려내서 검색하기 위한 가상의 테이블(검색 전용, 튜플의 수정, 삭제 불가능). 사용자 정의 테이블
--CREATE VIEW로 만들면 속성의 수정이 불가능하다.
--CREATE OR REPLACE VIEW로 생성하면 속성을 바꾸고 싶을 때 수정을 할 수 있다.

-- 예제) JOB_ID가 'ST_CLERK'인 데이터만 검색하는 VIEW를 만들어보자
CREATE OR REPLACE VIEW EMP_VIEW1(EMPNO, NAME, HIREDATE, JOB, DEPTNO) AS
SELECT EMPLOYEE_ID, FIRST_NAME, HIRE_DATE, JOB_ID, DEPARTMENT_ID
FROM EMPLOYEES
WHERE JOB_ID = 'ST_CLERK';

-- 생성된 VIEW 테이블에서 검색 가능하다.
SELECT *
FROM EMP_VIEW1;

CREATE OR REPLACE VIEW EMP_VIEW1(EMPNO, FULLNAME, HIREDATE, JOB, DEPTNO) AS
SELECT EMPLOYEE_ID, FIRST_NAME||LAST_NAME, HIRE_DATE, JOB_ID, DEPARTMENT_ID
FROM EMPLOYEES
WHERE JOB_ID = 'IT_PROG';

