--메모 정보를 관리하는 테이블 생성
CREATE TABLE MEMO_T(
	IDX NUMBER(3) PRIMARY KEY, -- 일련번호
	TITLE VARCHAR2(100) NOT NULL, -- 제목
	CONTENT VARCHAR2(4000), -- 내용
	PWD VARCHAR2(20) UNIQUE NOT NULL, -- 비밀번호
	IP VARCHAR2(30) NOT NULL, -- IP주소	
	WRITE_DATE DATE --작성일
);

-- # UPDATE : 튜플 수정
UPDATE MEMO_T
SET PWD = '1234', TITLE = 'TITLE3';
WHERE IDX = 1111;	--기본키가 1111인 튜플
COMMIT;
